---
apiVersion: v2
name: phpipam
description: "phpipam is an open-source web IP address management application (IPAM).
Its goal is to provide light, modern and useful IP address management.
It is php-based application with MySQL database backend, using jQuery libraries,
ajax and HTML5/CSS3 features."
type: application
version: 1.0.3
appVersion: "1.5.2"
