---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-web
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: "{{ .Release.Name }}-{{ .Chart.Name }}-cert"
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.phpipam.name }}
                port:
                  number: {{ .Values.phpipam.service.port }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ .Values.global.domain }}
  dnsNames:
    - {{ .Values.global.domain }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: "{{ .Release.Name }}-{{ .Chart.Name }}-cert"
